# Generated by Django 3.1.7 on 2021-03-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeuai', models.CharField(max_length=8)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=32)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=32)),
                ('lycee', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=128)),
                ('ppi', models.CharField(max_length=16)),
                ('annee_d_individualisation', models.IntegerField()),
                ('titreoperation', models.CharField(max_length=256)),
                ('enveloppe_prev_en_meu', models.DecimalField(decimal_places=6, max_digits=32)),
                ('montant_des_ap_votes_en_meu', models.DecimalField(decimal_places=6, max_digits=32)),
                ('mandataire', models.CharField(max_length=128)),
                ('maitrise_d_oeuvre', models.CharField(max_length=256)),
                ('notification_du_marche', models.DateField()),
                ('entreprise', models.CharField(max_length=256)),
                ('mode_de_devolution', models.CharField(max_length=128)),
                ('nombre_de_lots', models.IntegerField()),
                ('cao_attribution', models.DateField()),
                ('etat_d_avancement', models.CharField(max_length=128)),
                ('annee_de_livraison', models.IntegerField()),
            ],
        ),
    ]
