# Generated by Django 3.1.7 on 2021-03-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='annee_de_livraison',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cao_attribution',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='entreprise',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='mandataire',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='mode_de_devolution',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='nombre_de_lots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='notification_du_marche',
            field=models.DateField(null=True),
        ),
    ]
