# Generated by Django 3.1.7 on 2021-03-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20210312_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='enveloppe_prev_en_meu',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='montant_des_ap_votes_en_meu',
            field=models.DecimalField(decimal_places=6, max_digits=32, null=True),
        ),
    ]
