# Generated by Django 3.1.7 on 2021-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20210312_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='annee_d_individualisation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=32, null=True),
        ),
    ]
